apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wow-landingzone-lz1
  namespace: landingzones-sandpit
spec:
  releaseName: wow-landingzone-lz1
  targetNamespace: lz1
  interval: 2m
  install:
    remediation:
      retries: 3
  chart:
    spec:
      chart: wow-landingzone
      version: \"0.2.25\"
      sourceRef:
        kind: HelmRepository
        name: wow-oci
        namespace: flux-system
  values:
    version: \"0.1\"
    name: \"WDigital Landing Zone Test Service 1\"
    tla: \"lz1\"
    appServiceId: \"SNSVC0013226\"
    costCentre: \"\"
    team:
      name: \"CloudEngineering\"
      email: \"wooliesx-azure-foundations_at_woolworths.com.au\"
    environment: \"dev\"
    region: \"aae\"
    externalSecrets:
      tenantId: \"c28b2d80-129e-4693-88bd-5f43e59072f9\"
      serviceIdentityId: "abj"
      serviceKeyVaultURL: \"https://sandpit-dev-lz1-kv.vault.azure.net/\"
