require 'albacore'
require 'fileutils'
require 'rubygems'
require 'fileutils'

# utility functions for manipulating environment variables
def set_env(key, value)
  if false == value
    value = 'FALSE'
  elsif true == value
    value = 'TRUE'
  end
  ENV[key.to_s.upcase] = value
end

def get_env(key)
  val = ENV[key.to_s.upcase]
  if 'FALSE' == val
    val = false
  elsif 'TRUE' == val
    val = true
  end
  val
end

# Specify the device to use (in case there are multiple devices attached to computer)
#set_env(:adb_device_arg, '192.168.56.101:5555') # Genymotion, Galaxy S4 w/Android 4.2.2
#set_env(:adb_device_arg, 'HT9CXP812164')        # Hardware, Nexus One
#set_env(:adb_device_arg, '0149B2EC03012005')    # Hardware, Galaxy Nexus
set_env(:adb_device_arg, '192.168.56.102:5555') # Genymotion, Nexus 4 w/Android 4.3

task :default => [:clean, :build]

desc "Cleans the project"
task :clean => [:clean_screenshots] do
  directories_to_delete = [
      "./bin",
      "./obj",
      "./screenshots",
      "./test_servers",
      "./testresults.html"
  ]

  directories_to_delete.each { |x|
    rm_rf x
  }
end

desc "Delete the existing screen shots and calabash reports."
task :clean_screenshots do
  directories_to_delete = [
      "./screenshots/",
  ]

  directories_to_delete.each { |directory|
    rm_rf directory
  }
end

desc "Compiles a debug version of the project."
xbuild :build_android => [:clean] do |csproject|
  csproject.solution = "./Tasky.Android/Tasky.Android.csproj"
  csproject.properties = {:configuration => :release}
  csproject.targets [:Clean, :Build, :SignAndroidPackage]
end

desc "Runs calabash-android"
task :test_android => [:clean_screenshots] do
  mkdir './screenshots/' unless Dir.exists?('./screenshots/')
  set_env(:screenshot_path, './screenshots/')
  # --format html --out testresults.html
  `calabash-android run ./Tasky.Android/bin/Release/com.xamarin.samples.taskydroid-Signed.apk -p android ./features/add_new_task.feature`
end